services/web-app/components/back-to-top/back-to-top.js, services/web-app/components/back-to-top/back-to-top.module.scss, services/web-app/components/back-to-top/index.js, services/web-app/layouts/layout/layout.js, services/web-app/stories/components/back-top-top.stories.js
Closes #769 
**New**
- Back to top button
Make sure back to top matches style and functionality on [Gatsby theme ](https://gatsby-theme-carbon.vercel.app/demo) (interior pages, Gatsby theme homepage is dark so the button tokens are different)
=> feat(web-app): add back to top button

services/web-app/components/footer/footer.js
Closes #470
Remove date from footer
=> feat: remove date from footer

services/web-app/components/nav-primary/nav-primary.js, services/web-app/layouts/layout/layout.js
Closes #913
**Changed**
- Only displays the header nav if there are nav items to display
Check that navigation looks correct at all breakpoints.
=> fix(web-app): mobile nav spacing

services/web-app/components/asset-catalog-item/asset-catalog-item.js, services/web-app/components/asset-catalog-item/asset-catalog-item.module.scss, services/web-app/components/assets-catalog/assets-catalog.js, services/web-app/data/filters.js, services/web-app/data/libraries.mjs, services/web-app/data/teams.js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.module.scss, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.module.scss, services/web-app/pages/libraries/index.js, services/web-app/pages/libraries/index.module.scss, services/web-app/typedefs.js, services/web-app/types.js
Closes #951
http://localhost:3000/libraries/carbon-components-svelte/latest
http://localhost:3000/libraries/carbon-components-svelte/latest/assets/button
=> feat(web-app): rename sponsor to maintainer

services/web-app/components/catalog-sort/catalog-sort.module.scss, services/web-app/components/color-token-table/color-token-table.module.scss, services/web-app/components/svg-libraries/svg-library.module.scss, services/web-app/components/typeset-style/typeset-style.module.scss, services/web-app/styles/_variables.scss
Closes #931
**New**
- `$drop-shadow` variable
**Changed**
- Replaced shadows across site with new variable
- Fix for width of spacer above typeset sticky bar
Make sure drop shadows are consistent across the site
http://localhost:3000/elements/color/usage
http://localhost:3000/elements/icons/library
http://localhost:3000/elements/pictograms/library
http://localhost:3000/elements/typography/type-sets
http://localhost:3000/catalogs/components
=> fix(web-app): create drop shadow variable for consistent shadows

services/web-app/components/catalog/catalog.js, services/web-app/components/library-catalog-item/index.js, services/web-app/components/library-catalog-item/library-catalog-item.js, services/web-app/components/library-catalog-item/library-catalog-item.module.scss, services/web-app/components/library-catalog/index.js, services/web-app/components/library-catalog/library-catalog.js, services/web-app/data/filters.js, services/web-app/pages/libraries/index.js, services/web-app/pages/libraries/index.module.scss
Closes #371 
**New**
- LibraryCatalog Component
**Changed**
- Refactored libraries page to use LibraryCatalog component
- small tweak on sort to Catalog component
Test search and filter, make sure the individual library card looks same as in prod:
http://localhost:3000/libraries
Ensure still works/looks the same as prod:
http://localhost:3000/catalogs/components
http://localhost:3000/catalogs/patterns
http://localhost:3000/catalogs/templates
http://localhost:3000/catalogs/functions
http://localhost:3000/collections/data-visualization
=> feat(web-app): create library catalog component

services/web-app/esbuild.mjs, services/web-app/package.json, services/web-app/proxy-server.mjs
=> fix(web-app): proxy server conversion to esm

services/web-app/components/asset-catalog-item/asset-catalog-item.module.scss, services/web-app/components/back-to-top/back-to-top.module.scss, services/web-app/components/catalog-sort/catalog-sort.module.scss, services/web-app/components/color-token-table/color-token-table.module.scss, services/web-app/components/library-catalog-item/library-catalog-item.module.scss, services/web-app/components/page-breadcrumb/page-breadcrumb.module.scss, services/web-app/components/page-header/page-header.module.scss, services/web-app/components/page-nav/page-nav.module.scss, services/web-app/components/page-tabs/page-tabs.module.scss, services/web-app/components/resource-card/resource-card.module.scss, services/web-app/components/svg-libraries/svg-library.module.scss, services/web-app/components/typeset-style/typeset-style.module.scss, services/web-app/styles/vendor/_overrides.scss
Closes #1079
Make sure storybook compiles / loads http://localhost:6006/
Note: pages are still not loading, issue opened here https://github.com/carbon-design-system/carbon-platform/issues/1080
=> fix(web-app): storybook compile error

services/web-app/data/libraries.mjs
=> fix(web-app): remove mock library from devLibraries

services/web-app/lib/github.js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js
Closes #1023
**Changed**
- Library assets -> assets for heading
- latest -> latest version in side nav
http://localhost:3000/libraries/carbon-components-angular/latest/assets
=> fix(web-app): update library side nav and page heading

services/web-app/pages/about-carbon/releases.mdx
Closes #
#880 
**Changed**
- Minor content change based on #880 
- Quick content check
=> fix: content in release page

services/web-app/components/nav-secondary/nav-secondary.module.scss, services/web-app/components/nav-tree/nav-tree.module.scss
Closes #1059
Check that spacing and link matches spec
http://localhost:3000/libraries/carbon-components-angular/latest/assets
=> fix(web-app): library side nav style and spacing fix

services/web-app/components/dashboard/dashboard.module.scss, services/web-app/lib/github.js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
Closes #1039 
**New**
- add related libraries to library dashboard
- add correct right padding to dashboard items
Check that related library links are correct and working
http://localhost:3000/libraries/carbon-charts-angular
=> feat(web-app): add related libraries to dashboard

services/web-app/components/code/code.js
Closes #1129
Test that code snippet background displays correctly.
http://localhost:3000/mdx/code
_for the record, this wasn't what I thought it was, I didn't break it_ 🤣
=> fix(web-app): code snippet background bug

services/web-app/components/nav-tree/nav-tree.js
closes #1082
Check that active nav state is acting correctly on pages with and without tabs, and library nav
http://localhost:3000/guidelines/accessibility/keyboard
http://localhost:3000/developing
http://localhost:3000/libraries/carbon-components-angular/latest/assets
=> fix(web-app): active nav state

services/web-app/pages/about-carbon/how-carbon-works.mdx
Closes #1135 
- Deleted return between paragraphs
=> fix: copy update

services/web-app/pages/contributing/schema.mdx
=> add $ref guidance to schema docs

services/web-app/components/code/code.module.scss
closes #1129
Check multi line code snippets at medium breakpoint
http://localhost:3000/libraries/carbon-components-angular/latest/pages/tutorial/step-1
=> fix(web-app): code snippet width at md breakpoint

services/web-app/components/asset-catalog-item/asset-catalog-item.js, services/web-app/data/libraries.mjs
Closes #1204
**New**
- add default maintainer to libraries
**Changed**
- cleanup asset maintainer icon logic
**Removed**
- {{ Removed thing }}
test maintainer icon tooltip and make sure non-community assets still work as expected
http://localhost:3000/assets/components?maintainer[]=community
=> fix(web-app): fixes undefined maintainer in library

services/web-app/components/nav-tree/nav-tree.js
closes #1285
Ensure nav works correctly, and that nodes have unique ids so anchor link works correctly on FAQ / About Carbon Page and doesn't interact with left nav.
http://localhost:3000/about-carbon/help/faq
@jdharvey-ibm I went back and re-added your changes to this file
=> fix(web-app): set unique id for treeview nodes

services/web-app/data/nav-data.js
closes #1288
Make sure left nav stays active on all three tabbed pages in the section
http://localhost:3000/migrating/guide/overview
=> fix(web-app): active nav state for migrating section

services/web-app/components/catalog-search/catalog-search.module.scss
Closes #1323 
http://localhost:3000/assets/functions
=> fix(web-app): border subtle in catalog search

services/web-app/pages/index.js
closes #1305
Check that homepage h2 styling didn't change and anchor links are gone on hover
http://localhost:3000/
=> fix(web-app): remove anchor links from homepage h2

services/web-app/components/design-kit-catalog-item/design-kit-catalog-item.module.scss
closes #1306
Add focus state to catalog
Test that you can keyboard through items and focus state is correct
http://localhost:3000/design-kits
=> fix(web-app): focus state for catalog

services/web-app/components/nav-tree/nav-tree.js
closes #1291
Test that left nav works with keyboard and mouse
=> fix(web-app): open nav links with keyboard

services/web-app/components/do-dont/do-dont.module.scss, services/web-app/components/markdown/image.module.scss
Closes #1427
**New**
- Add top spacing for DoDontRow
**Changed**
- Fix classname for image styles
Check the dodont components have top spacing and that images don't hang left in the grid
http://localhost:3000/elements/2x-grid/overview
=> fix(web-app): dodont and image spacing bugs

services/web-app/components/banner/banner.module.scss
Closes #1421
**Changed**
- add correct css selector to position nav on homepage with banner
Check nav position on mobile on homepage and any inner page
http://localhost:3000/
=> fix(web-app): side nav homepage mobile position

services/web-app/components/catalog-sort/catalog-sort.module.scss
Closes #1433
**Changed**
- Catalog selected button styles
http://localhost:3000/assets/components
=> fix(web-app): catalog view icon hover and focus stlye fix

services/web-app/components/nav-tree/nav-tree.js
Closes #1361
**Changed**
- ActiveItem logic in navtree
Test both sidenavs
=> fix(web-app): sidenav, keep active item on parent selection

services/web-app/components/typeset-style/typeset-example.js, services/web-app/components/typeset-style/typeset-style.js
Closes #1341
http://localhost:3000/elements/typography/type-sets
=> fix(web-app): broken logic in typesets component

services/web-app/components/banner/banner.module.scss
closes #1476
Check nav position on homepage when opening/closing nav items, check all breakpoints
=> fix(web-app): nav position onclick
