services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js, services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.module.scss
Closes #856
Add correct top margin to library detail page
http://localhost:3000/assets/carbon-charts
Margin should be 5rem and match other pages
=> fix(web-app): top margin library detail page

services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].module.scss
Closes #877
**Removed**
- unnecessary left value for border
Check that tab bottom border displays full width on asset detail page. 
http://localhost:3000/assets/carbon-charts/latest/area-stacked
=> fix(web-app): asset detail page tab bottom border width

services/web-app/data/teams.js
Closes #895
**Changed**
- Updated teams data to pull icon from `@carbon/icons-react`
=> fix(web-app): replace dotcom and ibm products icons with src from carbon

services/web-app/components/svg-libraries/pictogram-library/pictogram-category.js
Closes #924 
**Changed**
- Added correct classname to pictogram library, should now pull in styles to display as 4 column at large+ breakpoint
Make sure Pictogram grid is 4 across at large+
http://localhost:3000/elements/pictograms/library
=> fix(web-app): set correct classname for pictogram grid

services/web-app/next.config.mjs
Output standalone is no longer experimental, see:
https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files
Fixes: 
**Changed**
- next.config.mjs
=> fix(web-app): next config output standalone experimental fix

services/web-app/data/type.js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js
Fixes logical error on library assets page that prevented Design only tag from showing up 
**Changed**
- services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js: fix if statement condition
http://localhost:3000/libraries/carbon-charts/latest/assets: validate design tags
=> fix(web-app): display design only tag in library assets

services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
Closes #1051 
**Changed**
- Moved library name inside of link
Check that library name is clickable on any component detail page 
http://localhost:3000/libraries/ibm-cloud-cognitive/latest/assets/action-bar
=> fix(web-app): make library name clickable

services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
Closes #1041
Add design kit links to library and asset dashboards
Add placeholder related libraries to library detail for correct spacing
http://localhost:3000/libraries/carbon-charts/latest
http://localhost:3000/libraries/carbon-charts/latest/assets/alluvial
=> feat(web-app): add design kit links to dashboard

services/web-app/components/color-token-table/color-token-table.js, services/web-app/components/color-token-table/color-token-table.module.scss
Closes #765
**Removed**
- most of the style overrides for content switcher (except border radius)
- 
Check that animation matches core Carbon https://react.carbondesignsystem.com/?path=/story/components-contentswitcher--playground&args=size:lg
http://localhost:3000/elements/color/usage
=> fix(web-app): remove style overrides content switcher

services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
Closes #1038 
**New**
- Add anchor links to library detail, always show dashboard and resources, only show demo links if there are demo links.
Test library with and without demo links
http://localhost:3000/libraries/ibmdotcom-web-components#dashboard
http://localhost:3000/libraries/ibm-cloud-cognitive
=> feat(web-app): add anchor links to library detail page

services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.module.scss
Closes #1043 
Update arrow color/fill on asset table. (should not be blue)
http://localhost:3000/libraries/carbon-charts/latest/assets
=> fix(web-app): arrow icon color

services/web-app/layouts/layout/layout.module.scss
Closes #1078
**Changed**
- update side nav z-index so it sits above page tabs
http://localhost:3000/guidelines/accessibility/overview
Test with scrollbars on and off and make sure pages with tabs render correctly
=> fix(web-app): update side nav z-index to fix tab bg overlay with scrollbar

services/web-app/components/resource-card/resource-card.js
Fixes the warning being output in the web-app when using the resource-card without specifying `color: 'dark'` as a prop. The default color will be 'light' and will use the g10 theme.
=> fix(web-app): resource-card default theme color

services/web-app/pages/about-carbon/faq/index.mdx
Closes #781
We originally pulled in the CDS FAQ page, but have now updated the content to better match with the Carbon Next site. 
**Changed**
- [See Figma](https://www.figma.com/file/FpVufniwvHjpMLdnBUshsE/FAQ-Page?node-id=0%3A1) for notes on what was changed.
- Read through the page. Is the information provided accurate for V1? (the FAQ will be updated once we have login/teams)
- Check links. Are links within the site formatted correctly?
- This page only contains headers and body text so no need for visual review.
=> fix: rewrite FAQ page

services/web-app/components/preview/preview.js, services/web-app/components/storybook-demo/storybook-demo.js, services/web-app/components/video/video.js
closes #1172
- Add sandbox prop to all components using iframes. (Video, Preview, StorybookDemo)
**Removed**
- prop spread to iframe inside of Preview component
Make sure the following components still render as expected
- Video http://localhost:3000/elements/2x-grid/overview
- Preview http://localhost:3000/mdx/preview
- StorybookDemo http://localhost:3000/mdx/storybook-demo
=> feat(web-app): lock down iframe props

services/web-app/pages/designing/get-started.mdx
Closes #1197 
This fixes the spacing issue on the `design / get-started` page - by removing the `TODO` comment - which will now be tracked here: https://github.com/carbon-design-system/carbon-platform/issues/919
- http://localhost:3000/designing/get-started
=> fix: get started spacing bug

services/web-app/lib/github.js
Closes #1217 
Issue was happening when data for relatedLibs could not be obtained successfully (item inside `otherLibraries` array was `null` , added condition to only include lib in relatedLibs array if details were successfully retrieved
**Changed**
- services/web-app/lib/github.js: added condition to skip non-complete libs for `getLibraryRelatedLibs`
1 - While on `main`, replace this part in `getLibraryRelatedLibs`
```
const relatedLibData = await getLibraryData({
library: slug,
ref: 'latest',
...libraryParams
})
``` 
with
```
const relatedLibData =  null
```
2 - Load http://localhost:3000/libraries/carbon-components-angular, confirm you're able to reproduce the error
3 - Checkout to `1217-web-app-nullpointerexception-in-library-details-on-api-rate-limiting`
4 -  replace this part in …
=> fix(web-app): only include related library if not null and with content

services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.module.scss
closes #1294
Test that filter dropdown text in catalogs is using correct type token (body-compact-01)
http://localhost:3000/assets/functions
=> fix(web-app): filter text font size

services/web-app/components/resource-card/resource-card-group.module.scss
closes #1297
- remove top border at mobile above resource card
Test at mobile http://localhost:3000/data-visualization/get-started
=> fix(web-app): remove border-top resource card on mobile

services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.module.scss
closes #1339
Check left padding for sort by at all breakpoints
http://localhost:3000/libraries/carbon-components-angular/latest/assets
=> fix(web-app): sort by left padding on asset list

services/web-app/components/library-catalog-item/library-catalog-item.js, services/web-app/components/library-catalog-item/library-catalog-item.module.scss, services/web-app/components/library-catalog/library-catalog.js
Closes #1301
We actually steered away from the gh pages route and are now deploying directly to an IBM Cloud Object Storage bucket that servers the files as a static website, which saves us the trouble of having to create a new repository to host the files 🔥 .
We'll do the same thing for pr storybook deployments using a different bucket
http://localhost:3000/libraries
=> fix(web-app): remove top border in library catalog first item

services/web-app/components/nav-tree/nav-tree.module.scss
Closes #1287
**Changed**
- treeview nav styles
Test navigation, section headings should no longer take on active class styles (no background or blue left border)
=> fix(web-app): remove nav active state from section headings

services/web-app/components/asset-details/asset-details.js, services/web-app/components/asset-details/asset-details.module.scss, services/web-app/components/content-wrapper/content-wrapper.js, services/web-app/components/content-wrapper/content-wrapper.module.scss, services/web-app/components/content-wrapper/index.js, services/web-app/components/mdx-page/mdx-page.js, services/web-app/components/svg-libraries/svg-library.module.scss, services/web-app/layouts/layout/layout.js, services/web-app/pages/about-carbon/platform-roadmap.js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/[tab].js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/[tab].module.scss, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/design-kits.js, services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js, services/web-app/pages/libraries/index.js
closes #1215
New `ContentWrapper` component.
- The intention is for any page content, mdx or otherwise to be wrapped in this component for consistent top spacing. 
This component was NOT added to any of the catalog pages for now, those pages have a different top spacing because the search bar is the first element. 
Check mdx pages, js page and remote mdx pages, pages with/without tabs etc. 
http://localhost:3000/elements/icons/library
http://localhost:3000/libraries/carbon-react/latest/assets/accordion
http://localhost:3000/libraries/carbon-react/latest/assets/accordion/style
http://localhost:3000/libraries/carbon-react/latest/assets/accordion/usage
http://localhost:3000/libraries/carbon-react/latest/assets/accordion/accessibility
http://localhost:3000/about-carbon/releases …
=> feat(web-app): add global content wrapper for consistent spacing

services/web-app/components/mdx-page/errors/content-not-found-exception-content.js, services/web-app/config/redirects.mjs, services/web-app/data/remote-pages.js, services/web-app/pages/common-mdx-errors/index.js
Found during an audit of remote MDX, this page is broken: https://next.carbondesignsystem.com/elements/typography/styling-strategies
**New**
- N/A
**Changed**
- Branch of `carbon-website` used to index the Styling strategies page
- "GitHub" and "URLs" capitalization in the MDX errors
**Removed**
- N/A
=> fix: indexed path for style strategies page

services/web-app/components/nav-tree/nav-tree.module.scss
Closes #1527 
Rotates treeview icon 180 deg on treenode expanded so chevron points up
**Changed**
- services/web-app/components/nav-tree/nav-tree.module.scss: add rule
test side nav open/close anywhere within the app, everything else should work as expected
=> fix(web-app): chevron up on treeview expanded

services/web-app/components/nav-tree/nav-tree.module.scss
Think I got it right this time :) (but also please test this 🤣 🙏 )
Reference: https://github.com/carbon-design-system/carbon-platform/commit/56a0e338ca1258bb650b11e6c82469d6d55fe660#diff-f41da72055179eda1ed546caf5c9619111a0e86b21203e7ca4f5f01bf4e4ed2bL97
**Changed**
- services/web-app/components/nav-tree/nav-tree.module.scss: made class more specific so it doesn't target nested menu items
Run web-app and test side nav with nested items, make sure only the chevron of the menu item that you clicked on changes orientation on open/close
=> fix(web-app): add specifity to chevron up nav tree class

services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.js
Closes #1153 
Add necessary spacer columns (if any) to multiselect filter display so that the border shows up across the whole line.
**Changed**
- services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.js: add and use `addSpacerColumns` function
Test multiselect filter across different breakpoints, should behave the same except visually all line borders should go all the way down
http://localhost:3000/assets/patterns
http://localhost:3000/assets/components
http://localhost:3000/assets/functions
http://localhost:3000/assets/templates
=> fix(web-app): add spacer columns to catalog multiselect filter

services/web-app/components/mdx/components.js, services/web-app/data/remote-pages.js, services/web-app/pages/elements/typography/type-sets.js, services/web-app/pages/mdx/index.mdx, services/web-app/pages/mdx/typesetstyle.mdx
Closes #1507 
**Changed**
- /elements/typography/type-sets is now a local js page
**Removed**
- MDX examples and export of typesetstyle
http://localhost:3000/elements/typography/type-sets compare to https://next.carbondesignsystem.com/elements/typography/type-sets
=> feat(web-app): make typesetstyle a JS page

services/web-app/pages/migrating/guide/develop.mdx
Closes #1595
http://localhost:3000/migrating/guide/develop should have parity with https://carbondesignsystem.com/migrating/guide/develop
=> fix(web-app): update develop migration guide

services/web-app/pages/about-carbon/releases.mdx
Closes #1609 
Content Sync: use github projects link instead of zenhub for carbon roadmap
**Changed**
- services/web-app/pages/about-carbon/releases.mdx: update roadmap link and icon
https://carbondesignsystem.com/all-about-carbon/releases/#resources vs http://localhost:3000/about-carbon/releases#resources
=> fix(web-app): Content Sync - update carbon roadmap link and icon

services/web-app/components/page-not-found/page-not-found.js, services/web-app/components/page-not-found/page-not-found.module.scss
Closes #1778 
**Changed**
- Added css styling to fix vertical spacing in page not found component
- Minor HTML restructure changes in page not found component 
Verify vertical spacing in lg/sm breakpoints:
=> fix(web-app): fix page not found vertical spacing
